export const NATURE_IMAGES = [
  "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=1920",
  "https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&q=80&w=1920",
  "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&q=80&w=1920",
  "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&q=80&w=1920",
  "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&q=80&w=1920",
  "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?auto=format&fit=crop&q=80&w=1920",
  "https://images.unsplash.com/photo-1439853949127-fa647821eba0?auto=format&fit=crop&q=80&w=1920",
  "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&q=80&w=1920",
  "https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?auto=format&fit=crop&q=80&w=1920",
  "https://images.unsplash.com/photo-1444491741275-3747c53c99b4?auto=format&fit=crop&q=80&w=1920"
];

export const VERSES = [
  { text: "Camina por fe, no por vista.", author: "2 Corintios 5:7" },
  { text: "Todo lo puedo en Cristo que me fortalece.", author: "Filipenses 4:13" },
  { text: "El Señor es mi pastor, nada me faltará.", author: "Salmo 23:1" },
  { text: "No temas, porque yo estoy contigo.", author: "Isaías 41:10" },
  { text: "Confía en el Señor de todo corazón.", author: "Proverbios 3:5" },
  { text: "El amor todo lo sufre, todo lo cree, todo lo espera.", author: "1 Corintios 13:7" },
  { text: "La paz de Dios sobrepasa todo entendimiento.", author: "Filipenses 4:7" },
  { text: "Buscad primero el reino de Dios y su justicia.", author: "Mateo 6:33" },
  { text: "Para Dios no hay nada imposible.", author: "Lucas 1:37" },
  { text: "El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente.", author: "Salmo 91:1" },
  { text: "Lámpara es a mis pies tu palabra, y lumbrera a mi camino.", author: "Salmo 119:105" },
  { text: "Someteos a Dios; resistid al diablo y huirá de vosotros.", author: "Santiago 4:7" },
  { text: "Yo soy el camino, la verdad y la vida.", author: "Juan 14:6" },
  { text: "Bienaventurados los limpios de corazón, porque ellos verán a Dios.", author: "Mateo 5:8" },
  { text: "Estad quietos, y conoced que yo soy Dios.", author: "Salmo 46:10" },
  { text: "El corazón alegre hermosea el rostro.", author: "Proverbios 15:13" },
  { text: "Dios es nuestro amparo y fortaleza.", author: "Salmo 46:1" },
  { text: "Si Dios es por nosotros, ¿quién contra nosotros?", author: "Romanos 8:31" },
  { text: "Tu palabra es la verdad.", author: "Juan 17:17" },
  { text: "Mirad cuán bueno y cuán delicioso es habitar los hermanos juntos en armonía.", author: "Salmo 133:1" },
  { text: "El fruto del Espíritu es amor, gozo, paz, paciencia, benignidad...", author: "Gálatas 5:22" },
  { text: "Clama a mí, y yo te responderé.", author: "Jeremías 33:3" },
  { text: "Justificados, pues, por la fe, tenemos paz para con Dios.", author: "Romanos 5:1" },
  { text: "La fe es la certeza de lo que se espera, la convicción de lo que no se ve.", author: "Hebreos 11:1" },
  { text: "El gozo del Señor es vuestra fuerza.", author: "Nehemías 8:10" },
  { text: "Porque yo sé los pensamientos que tengo acerca de vosotros, dice el Señor.", author: "Jeremías 29:11" },
  { text: "Mas el que persevere hasta el fin, éste será salvo.", author: "Mateo 24:13" },
  { text: "El Señor guardará tu salida y tu entrada desde ahora y para siempre.", author: "Salmo 121:8" },
  { text: "Pedid, y se vos dará; buscad, y hallaréis.", author: "Mateo 7:7" },
  { text: "Mas a todos los que le recibieron, les dio potestad de ser hechos hijos de Dios.", author: "Juan 1:12" },
  { text: "Sed fuertes y valientes. No temáis ni os asustéis.", author: "Deuteronomio 31:6" },
  { text: "Puestos los ojos en Jesús, el autor y consumador de la fe.", author: "Hebreos 12:2" },
  { text: "La gracia del Señor Jesucristo sea con todos vosotros.", author: "Apocalipsis 22:21" }
];
