export const NATURE_IMAGES = [
  "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=1920",
  "https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&q=80&w=1920",
  "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&q=80&w=1920",
  "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&q=80&w=1920",
  "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&q=80&w=1920",
  "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?auto=format&fit=crop&q=80&w=1920",
  "https://images.unsplash.com/photo-1439853949127-fa647821eba0?auto=format&fit=crop&q=80&w=1920",
  "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&q=80&w=1920",
  "https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?auto=format&fit=crop&q=80&w=1920",
  "https://images.unsplash.com/photo-1444491741275-3747c53c99b4?auto=format&fit=crop&q=80&w=1920"
];

export const VERSES = [
  { text: "El amor es sufrido, es benigno; el amor no tiene envidia, el amor no es jactancioso, no se envanece; no hace nada indebido, no busca lo suyo, no se irrita, no guarda rencor.", author: "1 Corintios 13:4-5" },
  { text: "Estad siempre gozosos. Orad sin cesar. Dad gracias en todo, porque esta es la voluntad de Dios para con vosotros en Cristo Jesús.", author: "1 Tesalonicenses 5:16-18" },
  { text: "Por nada estéis afanosos, sino sean conocidas vuestras peticiones delante de Dios en toda oración y ruego, con acción de gracias. Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones y vuestros pensamientos en Cristo Jesús.", author: "Filipenses 4:6-7" },
  { text: "Jehová te bendiga, y te guarde; Jehová haga resplandecer su rostro sobre ti, y tenga de ti misericordia; Jehová alce sobre ti su rostro, y ponga en ti paz.", author: "Números 6:24-26" },
  { text: "Pero los que esperan a Jehová tendrán nuevas fuerzas; levantarán alas como las águilas; correrán, y no se cansarán; caminarán, y no se fatigarán.", author: "Isaías 40:31" },
  { text: "No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios que te esfuerzo; siempre te ayudaré, siempre te sustentaré con la diestra de mi justicia.", author: "Isaías 41:10" },
  { text: "Todas vuestras cosas sean hechas con amor.", author: "1 Corintios 16:14" },
  { text: "Y estas palabras que yo te mando hoy, estarán sobre tu corazón; y las repetirás a tus hijos, y hablarás de ellas estando en tu casa, y andando por el camino, y al acostarte, y cuando te levantes.", author: "Deuteronomio 6:6-7" },
  { text: "Porque yo sé los pensamientos que tengo acerca de vosotros, dice Jehová, pensamientos de paz, y no de mal, para daros el fin que esperáis.", author: "Jeremías 29:11" },
  { text: "Jehová es mi pastor; nada me faltará.", author: "Salmo 23:1" },
  { text: "Lámpara es a mis pies tu palabra, Y lumbrera a mi camino.", author: "Salmo 119:105" },
  { text: "Fíate de Jehová de todo tu corazón, Y no te apoyes en tu propia prudencia. Reconócelo en todos tus caminos, Y él enderezará tus veredas.", author: "Proverbios 3:5-6" },
  { text: "Mira que te mando que te esfuerces y seas valiente; no temas ni desmayes, porque Jehová tu Dios estará contigo en dondequiera que vayas.", author: "Josué 1:9" },
  { text: "Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien, esto es, a los que conforme a su propósito son llamados.", author: "Romanos 8:28" },
  { text: "No os conforméis a este siglo, sino transformaos por medio de la renovación de vuestro entendimiento, para que comprobéis cuál sea la buena voluntad de Dios, agradable y perfecta.", author: "Romanos 12:2" },
  { text: "Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas.", author: "Mateo 6:33" },
  { text: "Por tanto, id, y haced discípulos a todas las naciones, bautizándolos en el nombre del Padre, y del Hijo, y del Espíritu Santo.", author: "Mateo 28:19" },
  { text: "Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito, para que todo aquel que en él cree, no se pierda, mas tenga vida eterna.", author: "Juan 3:16" },
  { text: "Jesús le dijo: Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí.", author: "Juan 14:6" },
  { text: "Todo lo puedo en Cristo que me fortalece.", author: "Filipenses 4:13" },
  { text: "Es, pues, la fe la certeza de lo que se espera, la convicción de lo que no se ve.", author: "Hebreos 11:1" },
  { text: "Pero sed hacedores de la palabra, y no tan solamente oidores, engañándoos a vosotros mismos.", author: "Santiago 1:22" },
  { text: "El que no ama, no ha conocido a Dios; porque Dios es amor.", author: "1 Juan 4:8" },
  { text: "Y el Dios de esperanza os llene de todo gozo y paz en el creer, para que abundéis en esperanza por el poder del Espíritu Santo.", author: "Romanos 15:13" },
  { text: "Y Jehová va delante de ti; él estará contigo, no te dejará, ni te desamparará; no temas ni te intimides.", author: "Deuteronomio 31:8" },
  { text: "Así que, hermanos míos amados, estad firmes y constantes, creciendo en la obra del Señor siempre, sabiendo que vuestro trabajo en el Señor no es en vano.", author: "1 Corintios 15:58" },
  { text: "Y ahora permanecen la fe, la esperanza y el amor, estos tres; pero el mayor de ellos es el amor.", author: "1 Corintios 13:13" },
  { text: "Deléitate asimismo en Jehová, Y él te concederá las peticiones de tu corazón.", author: "Salmo 37:4" },
  { text: "Este es el día que hizo Jehová; Nos gozaremos y alegraremos en él.", author: "Salmo 118:24" },
  { text: "Encomienda a Jehová tus obras, Y tus pensamientos serán afirmados.", author: "Proverbios 16:3" },
  { text: "Tú guardarás en completa paz a aquel cuyo pensamiento en ti persevera; porque en ti ha confiado.", author: "Isaías 26:3" },
  { text: "Por la misericordia de Jehová no hemos sido consumidos, porque nunca decayeron sus misericordias. Nuevas son cada mañana; grande es tu fidelidad.", author: "Lamentaciones 3:22-23" },
  { text: "Así alumbre vuestra luz delante de los hombres, para que vean vuestras buenas obras, y glorifiquen a vuestro Padre que está en los cielos.", author: "Mateo 5:16" },
  { text: "Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.", author: "Mateo 11:28" },
  { text: "Y amarás al Señor tu Dios con todo tu corazón, y con toda tu alma, y con toda tu mente y con todas tus fuerzas. Este es el principal mandamiento.", author: "Marcos 12:30" },
  { text: "Y como queréis que hagan los hombres con vosotros, así también haced vosotros con ellos.", author: "Lucas 6:31" },
  { text: "Y conoceréis la verdad, y la verdad os hará libres.", author: "Juan 8:32" },
  { text: "El ladrón no viene sino para hurtar y matar y destruir; yo he venido para que tengan vida, y para que la tengan en abundancia.", author: "Juan 10:10" },
  { text: "Le dijo Jesús: Yo soy la resurrección y la vida; el que cree en mí, aunque esté muerto, vivirá.", author: "Juan 11:25" },
  { text: "Un mandamiento nuevo os doy: Que os améis unos a otros; como yo os he amado, que también os améis unos a otros.", author: "Juan 13:34" },
  { text: "Mas Dios muestra su amor para con nosotros, en que siendo aún pecadores, Cristo murió por nosotros.", author: "Romanos 5:8" },
  { text: "Porque la paga del pecado es muerte, mas la dádiva de Dios es vida eterna en Cristo Jesús Señor nuestro.", author: "Romanos 6:23" },
  { text: "Así que, hermanos, os ruego por las misericordias de Dios, que presentéis vuestros cuerpos en sacrificio vivo, santo, agradable a Dios, que es vuestro culto racional.", author: "Romanos 12:1" },
  { text: "No seas vencido de lo malo, sino vence con el bien el mal.", author: "Romanos 12:21" },
  { text: "De modo que si alguno está en Cristo, nueva criatura es; las cosas viejas pasaron; he aquí todas son hechas nuevas.", author: "2 Corintios 5:17" },
  { text: "Con Cristo estoy juntamente crucificado, y ya no vivo yo, mas vive Cristo en mí; y lo que ahora vivo en la carne, lo vivo en la fe del Hijo de Dios, el cual me amó y se entregó a sí mismo por mí.", author: "Gálatas 2:20" },
  { text: "Mas el fruto del Espíritu es amor, gozo, paz, paciencia, benignidad, bondad, fe, mansedumbre, templanza; contra tales cosas no hay ley.", author: "Gálatas 5:22-23" },
  { text: "Porque por gracia sois salvos por medio de la fe; y esto no de vosotros, pues es don de Dios; no por obras, para que nadie se gloríe.", author: "Efesios 2:8-9" },
  { text: "Antes sed benignos unos con otros, misericordiosos, perdonándoos unos a otros, como Dios también os perdonó a vosotros en Cristo.", author: "Efesios 4:32" },
  { text: "Por lo demás, hermanos míos, fortaleceos en el Señor, y en el poder de su fuerza.", author: "Efesios 6:10" },
  { text: "Por lo cual, animaos unos a otros, y edificaos unos a otros, así como lo hacéis.", author: "1 Tesalonicenses 5:11" },
  { text: "Mi carne y mi corazón desfallecen; Mas la roca de mi corazón y mi porción es Dios para siempre.", author: "Salmo 73:26" },
  { text: "Si confesamos nuestros pecados, él es fiel y justo para perdonar nuestros pecados, y limpiarnos de toda maldad.", author: "1 Juan 1:9" },
  { text: "Vestíos, pues, como escogidos de Dios, santos y amados, de entrañable misericordia, de benignidad, de humildad, de mansedumbre, de paciencia.", author: "Colosenses 3:12" },
  { text: "Y todo lo que hagáis, hacedlo de corazón, como para el Señor y no para los hombres.", author: "Colosenses 3:23" },
  { text: "Por tanto, nosotros también, teniendo en derredor nuestro tan grande nube de testigos, despojémonos de todo peso y del pecado que nos asedia, y corramos con paciencia la carrera que tenemos por delante, puestos los ojos en Jesús, el autor y consumador de la fe.", author: "Hebreos 12:1-2" },
  { text: "Someteos, pues, a Dios; resistid al diablo, y huirá de vosotros.", author: "Santiago 4:7" },
  { text: "Echando toda vuestra ansiedad sobre él, porque él tiene cuidado de vosotros.", author: "1 Pedro 5:7" },
  { text: "Bienaventurado el varón que no anduvo en consejo de malos, Ni estuvo en camino de pecadores, Ni en silla de escarnecedores se ha sentado; Sino que en la ley de Jehová está su delicia, Y en su ley medita de día y de noche.", author: "Salmo 1:1-2" },
  { text: "Sean gratos los dichos de mi boca y la meditación de mi corazón delante de ti, Oh Jehová, roca mía, y redentor mío.", author: "Salmo 19:14" },
  { text: "Gustad, y ved que es bueno Jehová; Dichoso el hombre que confía en él.", author: "Salmo 34:8" },
  { text: "Dios es nuestro amparo y fortaleza, Nuestro pronto auxilio en las tribulaciones.", author: "Salmo 46:1" },
  { text: "Echa sobre Jehová tu carga, y él te sustentará; No dejará para siempre caído al justo.", author: "Salmo 55:22" },
  { text: "En mi corazón he guardado tus dichos, Para no pecar contra ti.", author: "Salmo 119:11" },
  { text: "En todo tiempo ama el amigo, Y es como un hermano en tiempo de angustia.", author: "Proverbios 17:17" },
  { text: "Todo tiene su tiempo, y todo lo que se quiere debajo del cielo tiene su hora.", author: "Eclesiastés 3:1" },
  { text: "Cuando pases por las aguas, yo estaré contigo; y si por los ríos, no te anegarán. Cuando pases por el fuego, no te quemarás, ni la llama arderá en ti.", author: "Isaías 43:2" },
  { text: "Jehová está en medio de ti, poderoso, él salvará; se gozará sobre ti con alegría, callará de amor, se regocijará sobre ti con cánticos.", author: "Sofonías 3:17" },
  { text: "Bienaventurados los pobres en espíritu, porque de ellos es el reino de los cielos.", author: "Mateo 5:3" },
  { text: "Pedid, y se os dará; buscad, y hallaréis; llamad, y se os abrirá.", author: "Mateo 7:7" },
  { text: "Amarás al Señor tu Dios con todo tu corazón, y con toda tu alma, y con toda tu mente. Este es el primero y grande mandamiento. Y el segundo es semejante: Amarás a tu prójimo como a ti mismo.", author: "Mateo 22:37-39" },
  { text: "La paz os dejo, mi paz os doy; yo no os la doy como el mundo la da. No se turbe vuestro corazón, ni tenga miedo.", author: "Juan 14:27" },
  { text: "Yo soy la vid, vosotros los pámpanos; el que permanece en mí, y yo en él, éste lleva mucho fruto; porque separados de mí nada podéis hacer.", author: "Juan 15:5" },
  { text: "Nadie tiene mayor amor que este, que uno ponga su vida por sus amigos.", author: "Juan 15:13" },
  { text: "Pero recibiréis poder, cuando haya venido sobre vosotros el Espíritu Santo, y me seréis testigos en Jerusalén, en toda Judea, en Samaria, y hasta lo último de la tierra.", author: "Hechos 1:8" },
  { text: "Porque no nos ha dado Dios espíritu de cobardía, sino de poder, de amor y de dominio propio.", author: "2 Timoteo 1:7" },
  { text: "El sana a los quebrantados de corazón, Y venda sus heridas.", author: "Salmo 147:3" },
  { text: "Encomienda a Jehová tu camino, Y confía en él; y él hará.", author: "Salmo 37:5" },
  { text: "No te niegues a hacer el bien a quien es debido, Cuando tuvieras poder para hacerlo.", author: "Proverbios 3:27" },
  { text: "El da esfuerzo al cansado, y multiplica las fuerzas al que no tiene ningunas.", author: "Isaías 40:29" },
  { text: "Porque donde están dos o tres congregados en mi nombre, allí estoy yo en medio de ellos.", author: "Mateo 18:20" },
  { text: "Mas a todos los que le recibieron, a los que creen en su nombre, les dio potestad de ser hechos hijos de Dios.", author: "Juan 1:12" },
  { text: "Estas cosas os he hablado para que en mí tengáis paz. En el mundo tendréis aflicción; pero confiad, yo he vencido al mundo.", author: "Juan 16:33" },
  { text: "Y en ningún otro hay salvación; porque no hay otro nombre bajo el cielo, dado a los hombres, en que podamos ser salvos.", author: "Hechos 4:12" },
  { text: "Porque no me avergüenzo del evangelio, porque es poder de Dios para salvación a todo aquel que cree; al judío primeramente, y también al griego.", author: "Romanos 1:16" },
  { text: "Si Dios es por nosotros, ¿quién contra nosotros?", author: "Romanos 8:31" },
  { text: "Gozosos en la esperanza; sufridos en la tribulación; constantes en la oración.", author: "Romanos 12:12" },
  { text: "No os ha sobrevenido ninguna tentación que no sea humana; pero fiel es Dios, que no os dejará ser tentados más de lo que podéis resistir, sino que dará también juntamente con la tentación la salida, para que podáis soportar.", author: "1 Corintios 10:13" },
  { text: "Bástate mi gracia; porque mi poder se perfecciona en la debilidad. Por tanto, de buena gana me gloriaré más bien en mis debilidades, para que repose sobre mí el poder de Cristo.", author: "2 Corintios 12:9" },
  { text: "Airaos, pero no pequéis; no se ponga el sol sobre vuestro enojo.", author: "Efesios 4:26" },
  { text: "Estando persuadido de esto, que el que comenzó en vosotros la buena obra, la perfeccionará hasta el día de Jesucristo.", author: "Filipenses 1:6" },
  { text: "Todo lo que es verdadero, todo lo honesto, todo lo justo, todo lo puro, todo lo amable, todo lo que es de buen nombre; si hay virtud alguna, si algo digno de alabanza, en esto pensad.", author: "Filipenses 4:8" },
  { text: "Y todo lo que hacéis, sea de palabra o de hecho, hacedlo todo en el nombre del Señor Jesús, dando gracias a Dios Padre por medio de él.", author: "Colosenses 3:17" },
  { text: "Toda la Escritura es inspirada por Dios, y útil para enseñar, para redargüir, para corregir, para instruir en justicia.", author: "2 Timoteo 3:16" },
  { text: "Porque la palabra de Dios es viva y eficaz, y más cortante que toda espada de dos filos; y penetra hasta partir el alma y el espíritu, las coyunturas y los tuétanos, y discierne los pensamientos y las intenciones del corazón.", author: "Hebreos 4:12" },
  { text: "Acerquémonos, pues, confiadamente al trono de la gracia, para alcanzar misericordia y hallar gracia para el oportuno socorro.", author: "Hebreos 4:16" },
  { text: "Y si alguno de vosotros tiene falta de sabiduría, pídala a Dios, el cual da a todos abundantemente y sin reproche, y le será dada.", author: "Santiago 1:5" },
  { text: "Quien llevó él mismo nuestros pecados en su cuerpo sobre el madero, para que nosotros, estando muertos a los pecados, vivamos a la justicia; y por cuya herida fuisteis sanados.", author: "1 Pedro 2:24" },
  { text: "Mas el Dios de toda gracia, que nos llamó a su gloria eterna en Jesucristo, después que hayáis padecido un poco de tiempo, él mismo os perfeccione, afirme, fortalezca y establezca.", author: "1 Pedro 5:10" },
  { text: "He aquí, yo estoy a la puerta y llamo; si alguno oye mi voz y abre la puerta, entraré a él, y cenaré con él, y él conmigo.", author: "Apocalipsis 3:20" }
];
